version: "3.9"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: train_booking_db
      MYSQL_USER: trainuser
      MYSQL_PASSWORD: trainpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - train_booking_network
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  db_migrate:
    image: ghcr.io/pikabut0t/train-booking-app:latest
    command: >
      sh -c "
        echo 'Waiting for MySQL...';
        sleep 15;
        until nc -z mysql 3306; do echo 'Waiting for DB port...'; sleep 2; done;
        echo 'Running migrations...';
        python migrate.py;
        echo 'Migrations complete!'
      "
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: trainuser
      MYSQL_PASSWORD: trainpass
      MYSQL_DATABASE: train_booking_db
    networks:
      - train_booking_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3

  flask_app:
    image: ghcr.io/pikabut0t/train-booking-app:latest
    command: >
      sh -c "
        echo 'Waiting for MySQL DNS + port...';
        sleep 10;
        until getent hosts mysql; do sleep 2; done;
        until nc -z mysql 3306; do echo 'Waiting for port 3306...'; sleep 2; done;
        echo 'DB is ready!';
        gunicorn -b 0.0.0.0:5000 --workers 1 --timeout 120 'app:create_app()'
      "
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: trainuser
      MYSQL_PASSWORD: trainpass
      MYSQL_DATABASE: train_booking_db
    ports:
      - "8089:5000"
    networks:
      - train_booking_network
    healthcheck:
      disable: true
#      test: ["CMD", "curl", "-f", "http://localhost:5000/api/auth/check"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#      start_period: 40s
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 320M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10

networks:
  train_booking_network:
    driver: overlay

volumes:
  mysql_data:
