version: "3.9"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: train_booking_db
      MYSQL_USER: trainuser
      MYSQL_PASSWORD: trainpass
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - train_booking_network
    healthcheck:
      disable: true
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 5s
#      timeout: 3s
#      retries: 10
#      start_period: 30s
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  db_migrate:
    image: ghcr.io/pikabut0t/train-booking-app:latest
    command: >
      sh -c "
        echo 'Waiting for MySQL...';
        sleep 5;
        for i in 1 2 3 4 5 6 7 8 9 10; do
          nc -z mysql 3306 && break;
          echo 'Attempt '$$i': waiting for DB...';
          sleep 2;
        done;
        echo 'Running migrations...';
        python migrate.py;
        echo 'Migrations complete!'
      "
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: trainuser
      MYSQL_PASSWORD: trainpass
      MYSQL_DATABASE: train_booking_db
    networks:
      - train_booking_network
    depends_on:
      - mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3

  flask_app:
    image: ghcr.io/pikabut0t/train-booking-app:latest
    command: >
      sh -c "
        echo 'Waiting for MySQL...';
        for i in 1 2 3 4 5 6 7 8 9 10; do
          nc -z mysql 3306 && break;
          echo 'Attempt '$$i': waiting for DB...';
          sleep 2;
        done;
        echo 'DB is ready! Starting app...';
        exec gunicorn -b 0.0.0.0:5000 --workers 2 --threads 2 --timeout 120 --graceful-timeout 30 --keep-alive 5 --worker-class gthread 'app:create_app()'
      "
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: "3306"
      MYSQL_USER: trainuser
      MYSQL_PASSWORD: trainpass
      MYSQL_DATABASE: train_booking_db
    ports:
      - "8089:5000"
    networks:
      - train_booking_network
    depends_on:
      - mysql
      - db_migrate
    healthcheck:
      disable: true
#      test: ["CMD", "curl", "-f", "http://localhost:5000/api/auth/check"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#      start_period: 15s
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 320M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first

networks:
  train_booking_network:
    driver: overlay

volumes:
  mysql_data:
